### PR TITLE
Update plugin.yml

### PR DESCRIPTION
**Pull request by pandory-network**
fix dependency load order

### CODE REVIEW

**Comment by wysohn** [comment]
Hmm did it solve your problem?

softdepend would do the same, so I'm not quite sure what happened for your case

Make sure to have only one RapidFramework jar in the plugins folder though if you haven't checked yet

**Comment by pandory-network** [comment]
i have only one RapidFramework jar in the plugin folder. depend RapidFramework makes sure that the plugin is loaded before RealEconomy

**Comment by wysohn** [comment]
Yeah, but technically, softdepend would do the same anyway.

According to [this](https://bukkit.gamepedia.com/Plugin_YAML), `Your plugin will load after any plugins listed here.`

Actually, I had to change the project name from `RapidFramework` to `rapidframework` because Github suddenly changed their policy on uploading the package has to be in lower case, so I changed the project name to lower case. 

I later found a way to specify only the name of the uploaded package, not the name of the entire project; I changed the name to RapidFramework again. Obviously, I had to change softdepend for all other plugins that depending on it, and maybe that could be the problem. That's why I asked you to upload the .jar file so I can check if the dependency name is set as `rapidframework` or `RapidFramework`

Anyway, if you figured out how to work around it, that's great. But I can't really merge this PL as I don't see the difference.

**Comment by wysohn** [comment]
But in any case, since the plugin is strongly coupled with the RapidFramework, I will move it from softdepend to depend.

But it has to be done in gradle.build, not directly in the plugin.yml

**Pull request closed without merging**
